name: Manual Deploy to Netlify
on:
  push:
    branches:
      - main  # Runs every time you push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and Build
        run: |
          npm install
          npm run build  # Change this if your build command is different

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --prod --dir=dist --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}
        # Note: Change --dir=dist to your build folder (e.g., --dir=build or --dir=public)
